linters:
  disable-all: false
  fast: false
  enable:
    - golint
    - govet
    - megacheck
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - nestif
    - goconst
    - gocritic
    - nolintlint

    # TODO add to build scripts
    #- gofumpt
    #- gci

linters-settings:
  goconst:
    min-len: 10
    min-occurrences: 3
