severity:
  default-severity: warning
  case-sensitive: false

  rules:
    - linters:
        - errcheck
        - errorlint
        - nolintlint
        - wrapcheck
      severity: error

linters:
  disable-all: false
  fast: false
  enable:
    # seems broken
    #- bodyclose
    - deadcode
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - gomodguard
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - megacheck
    # too much work required right now
    #- nestif
    - nilerr
    #- nilnil
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  goconst:
    min-len: 10
    min-occurrences: 3

  gosec:
    severity: medium
    excludes:
      - G306
      - G107

  exhaustive:
    default-signifies-exhaustive: true

  nestif:
    min-complexity: 7

  typecheck:
    exclude:
      - 'could not import C (cgo preprocessing failed)'

  wrapcheck:
    ignoreSigs:
      # defaults from https://github.com/tomarrell/wrapcheck/blob/master/wrapcheck/wrapcheck.go
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      # ignore bbolt's Tx.ForEach() because it only returns the error from the passed callback
      - .ForEach(
      - .Update(
      - .View(
      - .Batch(
      # eris...
      - eris.New(
      - eris.Wrap(
      - eris.Wrapf(
      # starlark argument errors are fairly obvious even without an accurate stacktrace
      - starlark.UnpackPositionalArgs(
      - starlark.UnpackArgs(

    ignorePackageGlobs:
      - github.com/ngld/knossos/packages/*
