linters:
  disable-all: false
  fast: false
  enable:
    - golint
    - govet
    - megacheck
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - gci
    - nestif
    - goconst
    - gocritic
    - gofumpt
    - nolintlint
