linters:
  disable-all: false
  fast: false
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - gomodguard
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - megacheck
    - nestif
    - nilerr
    #- nilnil
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
    - wrapcheck

    # TODO add to build scripts
    #- gofumpt
    #- gci

linters-settings:
  goconst:
    min-len: 10
    min-occurrences: 3

  exhaustive:
    default-signifies-exhaustive: true

  nestif:
    min-complexity: 7

  wrapcheck:
    ignoreSigs:
      # defaults from https://github.com/tomarrell/wrapcheck/blob/master/wrapcheck/wrapcheck.go
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      # ignore bbolt's Tx.ForEach() because it only returns the error from the passed callback
      - .ForEach(
      - .Update(
      - .View(
      - .Batch(
      # eris...
      - eris.New(
      - eris.Wrap(
      - eris.Wrapf(

    ignorePackageGlobs:
      - github.com/ngld/knossos/packages/*
