plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  "@blueprintjs/popover2@*":
    peerDependencies:
      react-dom: "*"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
