// Code generated by "stringer -type=LogLevel"; DO NOT EDIT.

package libinnoextract

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogDebug-1]
	_ = x[LogInfo-2]
	_ = x[LogWarning-3]
	_ = x[LogError-4]
}

const _LogLevel_name = "LogDebugLogInfoLogWarningLogError"

var _LogLevel_index = [...]uint8{0, 8, 15, 25, 33}

func (i LogLevel) String() string {
	i -= 1
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
