name: Publish Updater

on:
  push:
    tags:
      - 'updater-v*'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.sha.outputs.short_sha }}
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
      go_version: ${{ steps.read.outputs.go_version }}
      msys2_packages: ${{ steps.read.outputs.msys2_packages }}
      updater_changed: ${{ steps.changes.outputs.updater_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate short SHA
        id: sha
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%d%m%H%M')"

      - name: Read build settings from repository
        id: read
        run: |
          go_version=$(< .go-version)
          echo "Go version: ${go_version}"
          echo "::set-output name=go_version::${go_version}"
          msys2_packages=$(tr -s '\n' ' ' < msys2-packages.txt)
          echo "MSYS2 packages: ${msys2_packages}"
          echo "::set-output name=msys2_packages::${msys2_packages}"

      - name: Detect changed files
        id: changes
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            base_ref="origin/${{ github.base_ref }}"
          elif [ "${{ github.event_name }}" = "push" ]; then
            base_ref="${{ github.event.before }}"
          else
            echo "Unsupported event ${{ github.event_name }}"
            exit 1
          fi

          changed="$(git diff --name-only "$base_ref..HEAD")"

          echo "::group::Changed files"
          echo "$changed"
          echo "::endgroup::"

          if grep -E '^packages/(libarchive|updater|build-tools)' > /dev/null <<< "$changed"; then
            echo "::set-output name=updater_changed::1"
          fi

  updater:
    name: Updater / ${{ matrix.os }}
    runs-on: ${{ matrix.runner }}
    needs: setup
    if: needs.setup.outputs.updater_changed == '1'
    strategy:
      fail-fast: false
      matrix:
        os: [Windows, macOS, Ubuntu]
        include:
          - os: Windows
            runner: windows-2019
            script: .\task.ps1
          - os: macOS
            runner: macos-10.15
            script: ./task.sh
          - os: Ubuntu
            runner: ubuntu-20.04
            script: ./task.sh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go toolchain
        uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.setup.outputs.go_version }}

      - name: Setup MSYS2 toolchain (Windows)
        uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          update: true
          install: ${{ needs.setup.outputs.msys2_packages }}

      - name: Locate MSYS2 installation (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          path=$(cygpath -w /)
          echo "MSYS2 is installed at ${path}"
          echo "extra_options=\"msys2_path=${path}\"" >> "$GITHUB_ENV"

      - name: Cache Go dependencies
        uses: actions/cache@v2
        with:
          key: golang-${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: golang-${{ github.job }}-${{ runner.os }}-
          path: |
            ~/go/pkg
            ~/.cache/go-build

      - name: Cache managed dependencies
        uses: actions/cache@v2
        with:
          key: third_party-${{ runner.os }}-${{ hashFiles('packages/build-tools/DEPS.yml') }}
          restore-keys: third_party-${{ runner.os }}-
          path: |
            packages/build-tools/DEPS.stamps
            third_party

      - name: Fetch system dependencies (*nix)
        if: runner.os != 'Windows'
        run: |
          if [ "$RUNNER_OS" = 'macOS' ]; then
            brew install xz
          elif [ "$RUNNER_OS" = 'Linux' ]; then
            sudo apt-get install -y libgtk-3-dev liblzma-dev libzstd-dev zlib1g-dev
          fi

      - name: Configure build
        run: ${{ matrix.script }} configure build=Release ${{ env.extra_options }}

      - name: Fetch managed dependencies
        run: ${{ matrix.script }} fetch-deps

      - name: Install build tools
        run: ${{ matrix.script }} install-tools

      - name: Build libarchive
        run: ${{ matrix.script }} libarchive-build

      - name: Build updater
        if: needs.setup.outputs.updater_changed == '1'
        run: ${{ matrix.script }} updater-build

      - name: Package updater (Windows)
        if: runner.os == 'Windows'
        run: cd build && zip -r updater.zip updater

      - name: Package updater (*nix)
        if: runner.os != 'Windows'
        run: cd build && tar -czf updater.tar.gz updater

      - name: Upload updater
        if: needs.setup.outputs.updater_changed == '1'
        uses: softprops/action-gh-release@v1
        with:
          files: build/updater.*
          name: Updater ${{ needs.setup.output.timestamp }}+${{ needs.setup.outputs.short_sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
